-- MySQL Administrator dump 1.4
--
-- ------------------------------------------------------
-- Server version	5.1.71-log


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


/* Change this to be the name of the drupal multisite database */
USE drupal1;

--
-- Definition of table `islandora_autocomplete`
--

DROP TABLE IF EXISTS `islandora_autocomplete`;
CREATE TABLE `islandora_autocomplete` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `description` varchar(256) NOT NULL,
  `source` varchar(64) NOT NULL,
  `fields` int(11) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  KEY `source` (`source`)
) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `islandora_autocomplete`
--

/*!40000 ALTER TABLE `islandora_autocomplete` DISABLE KEYS */;
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (5,'sp_ol_xxxx_pvocab_mads_usedfor_npvocab_mads_use','Controls the Object Linker processing for the \"Use For Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Use Term\" field on a Non-preferred Vocab MADS \"Object\" Record','sparql',1),
 (4,'sp_ol_xxxx_pvocab_mads_broader_pvocab_mads_narrower','Controls the Object Linker processing for the \"Broader Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Narrower Term\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (7,'sp_ol_xxxx_pdf_mods_vocabkeyw_pvocab_mads_xxxx','Controls the Object Linker processing for the \"Vocab Keyword\" on a PDF \"Subject\" Record linking to a Preferred Vocab \"Object\" Record.','sparql',1),
 (8,'sp_ol_xxxx_pvocab_mads_geokeyw_pgeovoc_mads_vocabkeyw','Controls the Object Linker processing for the \"Geographic Keyword\" field on a \"Preferred Vocab\" MADS Record linking to a \"Vocab Keyword\" field on a \"Preferred Geo\" MADS \"Object\" Record.','sparql',1),
 (9,'sp_ol_xxxx_pgeovoc_mads_vocabkeyw_pvocab_mads_geokeyw','Controls the Object Linker processing for the \"Subject Keyword\" field on a Preferred geoVocab \"Subject\" Record linking to a \"Geographic Keyword\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (10,'sp_ol_xxxx_pdf_mods_geokeyw_pgeovoc_mads_xxxx','Controls the Object Linker processing for the \"geographic keyword\" on a PDF \"Subject\" Record linking to a Preferred geoVocab \"Object\" Record.','sparql',1),
 (11,'sp_ol_xxxx_pvocab_mads_related_pvocab_mads_related','Controls the Object Linker processing for the \"Related Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Related Term\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (12,'sp_ol_xxxx_pvocab_mads_narrower_pvocab_mads_broader','Controls the Object Linker processing for the \"Narrower Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Broader Term\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (13,'sp_ol_xxxx_pgeovoc_mads_broader_pgeovoc_mads_narrower','Controls the Object Linker processing for the \"Broader Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Narrower Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (14,'sp_ol_xxxx_pgeovoc_mads_narrower_pgeovoc_mads_broader','Controls the Object Linker processing for the \"Narrower Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Broader Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (15,'sp_ol_xxxx_pgeovoc_mads_related_pgeovoc_mads_related','Controls the Object Linker processing for the \"Related Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Related Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (16,'sp_ol_xxxx_pgeovoc_mads_usedfor_npgeovoc_mads_use','Controls the Object Linker processing for the \"Used For Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Use Term\" field on a Non-preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (17,'sp_ol_xxxx_pgeovoc_mads_geofeature_pgeovoc_mads_isgeofeatureof','Controls the Object Linker processing for the \"Geographic Feature Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Is Geographic Feature Of Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (18,'sp_ol_xxxx_pgeovoc_mads_isgeofeatureof_pgeovoc_mads_geofeature','Controls the Object Linker processing for the \"Is Geographic Feature Of Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Geographic Feature Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (19,'sp_ol_xxxx_npgeovoc_mads_use_pgeovoc_mads_usedfor','Controls the Object Linker processing for the \"Use\" field on a Non-preferred geoVocab MADS \"Subject\" Record linking to a \"Used For\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (20,'sp_ol_xxxx_npvocab_mads_use_pvocab_mads_usedfor','Controls the Object Linker processing for the \"Use\" field on a Non-preferred Vocab MADS \"Subject\" Record linking to a \"Used For\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (21,'sp_ol_xxxx_pgeovoc_mads_creationdate_pdf_mods_xxxx','Controls the Object Linker processing for removing links between Preferred geoVocab \"Subject\" Records and PDF MADS \"Object\" Records when a Preferrred geoVocab Record is purged after one or more PDF Records have been linked to it. ','sparql',1),
 (22,'sp_ol_xxxx_pvocab_mads_creationdate_pdf_mods_xxxx','Controls the Object Linker processing for removing links between Preferred Vocab \"Subject\" Records and PDF MADS \"Object\" Records when a Preferrred Vocab Record is purged after one or more PDF Records have been linked to it. This autocomplete is relevant to','sparql',1);
/*!40000 ALTER TABLE `islandora_autocomplete` ENABLE KEYS */;


--
-- Definition of table `islandora_autocomplete_sparql`
--

DROP TABLE IF EXISTS `islandora_autocomplete_sparql`;
CREATE TABLE `islandora_autocomplete_sparql` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url_id` int(11) NOT NULL,
  `sparql_field` varchar(2048) NOT NULL,
  `rdf_relationship` varchar(256) NOT NULL,
  `object_pid_append_required` int(11) NOT NULL,
  `subject_dsid` varchar(128) NOT NULL,
  `subject_namespace_info` varchar(2048) NOT NULL,
  `subject_xpath_title_search` varchar(1024) NOT NULL,
  `subject_xpath_data_search` varchar(1024) NOT NULL,
  `object_creation_required` int(11) NOT NULL,
  `inverse_required` int(11) NOT NULL,
  `symmetry_in_object_datastream_required` int(11) NOT NULL,
  `object_dsid` varchar(128) NOT NULL,
  `object_namespace_info` varchar(2048) NOT NULL,
  `object_datastream_xml` varchar(4096) NOT NULL,
  `object_xpath_title_search` varchar(1024) NOT NULL,
  `object_xpath_date_create_search` varchar(1024) NOT NULL,
  `object_content_model_pid` varchar(256) NOT NULL,
  `object_collection_pid` varchar(256) NOT NULL,
  `object_namespace_prefix` varchar(256) NOT NULL,
  `object_transform` varchar(1024) NOT NULL,
  `object_state` varchar(128) NOT NULL,
  `object_xpath_data_search` varchar(1024) NOT NULL,
  `object_xpath_data_build` varchar(1024) NOT NULL,
  `object_xpath_data_build_countback` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `islandora_autocomplete_sparql`
--

/*!40000 ALTER TABLE `islandora_autocomplete_sparql` DISABLE KEYS */;
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`object_pid_append_required`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_creation_required`,`inverse_required`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (26,4,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#hasBroaderAuthority',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"broader\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic','/mads/related[@type=\"narrower\"]/topic','2'),
 (27,5,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabnonpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabnonpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#useFor',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><variant><topic></topic></variant><related otherType=\"use\" type=\"other\"><topic></topic></related><note type=\"approved date\"></note><recordInfo><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><identifier type=\"TNR\"></identifier></mads>','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabnonpref_CModel','fba:vocabnonpref_collection','vocabnonpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabnonpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"use\" and @type=\"other\" ]/topic','2'),
 (29,7,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasKeyword',0,'MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo/mods:title','/mods:mods/mods:subject[@authority=\"islandora subject\"]/mods:topic',0,1,0,'','','','','','fba:vocabpref_CModel','fba:vocabpref_collection','','','','','',''),
 (30,8,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasCorrelative',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"geographic keyword\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"subject keyword\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"subject keyword\" and @type=\"other\"]/topic','2'),
 (31,9,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasCorrelative',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"subject keyword\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"geographic keyword\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"geographic keyword\" and @type=\"other\"]/topic','2'),
 (32,10,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicKeyword',0,'MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo/mods:title','/mods:mods/mods:subject[@authority=\"islandora geographic\"]/mods:geographic',0,1,0,'','','','','','fba:geopref_CModel','fba:geopref_collection','','','','','',''),
 (38,16,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geononpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geononpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#useFor',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><variant><topic></topic></variant><related otherType=\"use\" type=\"other\"><topic></topic></related><note type=\"approved date\"></note><recordInfo><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo></mads>','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geononpref_CModel','fba:geononpref_collection','geononpref','./sites/all/modules/islandora_content_model_forms/transforms/geononpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"use\" and @type=\"other\"]/topic','2'),
 (33,11,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#hasRelatedAuthority',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[not(@*)]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[not(@*)]/mads:topic','/mads/related/topic','2'),
 (34,12,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#hasNarrowerAuthority',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"broader\"]/mads:topic','/mads/related[@type=\"broader\"]/topic','2'),
 (35,13,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#hasBroaderAuthority',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"broader\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic','/mads/related[@type=\"narrower\"]/topic','2'),
 (36,14,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#hasNarrowerAuthority',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"broader\"]/mads:topic','/mads/related[@type=\"broader\"]/topic','2'),
 (37,15,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#hasRelatedAuthority',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[not(@*)]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[not(@*)]/mads:topic','/mads/related/topic','2'),
 (39,17,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicFeature',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"geographic feature\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"is geographic feature of\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"is geographic feature of\" and @type=\"other\"]/topic','2'),
 (40,18,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isGeographicFeatureOf',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"is geographic feature of\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"geographic feature\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"geographic feature\" and @type=\"other\"]/topic','2'),
 (41,19,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#useInstead',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"used for\" and @type=\"other\"]/topic','2'),
 (42,20,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://www.loc.gov/mads/rdf/v1#useInstead',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic',1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic keyword\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"used for\" and @type=\"other\"]/topic','2'),
 (43,21,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/islandora:sp_strict_pdf>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/islandora:sp_pdf_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isGeographicKeywordedWith',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:authority/mads:topic',0,1,0,'','','','','','islandora:sp_strict_pdf','islandora:sp_pdf_collection','','','','','',''),
 (44,22,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/islandora:sp_strict_pdf>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/islandora:sp_pdf_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title LIMIT 10','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isKeywordedWith',0,'MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:authority/mads:topic',0,1,0,'','','','','','islandora:sp_strict_pdf','islandora:sp_pdf_collection','','','','','','');
/*!40000 ALTER TABLE `islandora_autocomplete_sparql` ENABLE KEYS */;


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;